spring:
  application:
    name: Wkanki
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: wkanki
      port: 27017
      host: localhost

#live
#wanikaniBaseURL: https://api.wanikani.com
authToken: test

#wiremock
wanikaniBaseURL: http://localhost:8095

